version: '3.8'

services:
  db:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appPassw0rd
      POSTGRES_DB: soon_development
    ports:
      - "5432:5432" # Expose PostgreSQL to local machine at localhost:5432
    healthcheck:
      #   test: [ "CMD", "pg_isready", "-U", "appuser" ]
      interval: 10s
      retries: 5
      timeout: 5s

  web:
    build: .
    command: [ "rails", "server", "-b", "0.0.0.0" ]
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "postgresql://appuser:appPassw0rd@db:5432/soon_development" # Uses 'db' as the hostname
    depends_on:
      - db

volumes:
  postgres_data:
